apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumingrest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumingrest
  template:
    metadata:
      labels:
        app: consumingrest
    spec:
      containers:
      - name: consumingrest
        image: jeffyf/consumingrest
        ports:
        - containerPort: 8080
        env:
        - name: quoters_base_url
          value: "http://quoters.default:8080"
          #if they are under the same namespace ->"http://quoters:8080"

# name.namespace.svc.cluster.local
# http://quoters:8080/